@hostname = localhost
@port = 8080

###

GET http://{{hostname}}:{{port}}/

###

GET http://{{hostname}}:{{port}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmM0YjQzY2U5Nzc2YjAyYzQ4MDc0MjUiLCJpYXQiOjE2MDc0MTQ2Mjl9.hpr_qgOyQtkozx6CUXWqxmwIW0s0JHhi891USPMY7fo

###

POST http://{{hostname}}:{{port}}/signup
content-type: application/json

{
  "name": "Lucas Kevin",
  "email": "lucasKevin@yahoo.com",
  "password": "lucas12345",
  "confirmPassword": "lucas12345"
}

###

post http://{{hostname}}:{{port}}/signin
Content-Type: application/json

{
  "email": "lucasKevin@yahoo.com",
  "password": "lucas12345"
}

###

PUT http://{{hostname}}:{{port}}/users/5fcf77def0b8b33a14af3e93
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmNmNzdkZWYwYjhiMzNhMTRhZjNlOTMiLCJpYXQiOjE2MDc0MzIxOTh9.qQqjLBCdVAj6y7mgrLJmGovlXO2qBtKrIYaYikYBsFc

{
   "name": "Zeph Friend",
   "email": "zeph190@gmail.com"
}

###

POST http://{{hostname}}:{{port}}/credentials
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmQxMmNlYmFiMDcyMzEwYjA1MGZlZDEiLCJpYXQiOjE2MDc1NDQwNzl9.2YvhtE845D35HyyLRNGUswK3ZWkb0XofuYa-l18f5Z4

{
  "name": "Lucas Kevin",
  "profilePic": "https://imageskjskdjflkajsdklfjalksdjflkajsdfkl",
  "contact": {
    "phone": "1234567890",
    "mobile": "1234567890"
  },
  "location": {
    "Content-Type: "
    "address": "Nitinda"
  }
}

###

GET http://{{hostname}}:{{port}}/localhost:8080/credentials/5fd12cebab072310b050fed1

