@hostname = localhost
@port = 8080

###

GET http://{{hostname}}:{{port}}/

###

GET http://{{hostname}}:{{port}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmM0YjQzY2U5Nzc2YjAyYzQ4MDc0MjUiLCJpYXQiOjE2MDc0MTQ2Mjl9.hpr_qgOyQtkozx6CUXWqxmwIW0s0JHhi891USPMY7fo

###

POST http://{{hostname}}:{{port}}/signup
content-type: application/json

{
  "name": "user2",
  "email": "user2@yahoo.com",
  "password": "user2@12345",
  "confirmPassword": "user2@12345"
}

###

post http://{{hostname}}:{{port}}/signin
Content-Type: application/json

{
  "email": "user2@gmail.com",
  "password": "user2@12345"
}

###

PUT http://{{hostname}}:{{port}}/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmZhM2EzNzJiNDZlMjFiZjc3ZDI4YWUiLCJlbWFpbCI6InVzZXIyQHlhaG9vLmNvbSIsIm5hbWUiOiJ1c2VyMiIsImlhdCI6MTYxMDI5NTE0Nn0.FHLFePthrRuEPjkG-V1PBcX1nspwtU3rh93hp9W0uIk

{
  "email": "user2@gmail.com"
}

###

POST http://{{hostname}}:{{port}}/credentials
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmZhM2EzNzJiNDZlMjFiZjc3ZDI4YWUiLCJlbWFpbCI6InVzZXIyQHlhaG9vLmNvbSIsIm5hbWUiOiJ1c2VyMiIsImlhdCI6MTYxMDIzNDUyM30.dodpgdyW_es_PuR7iNaK6Cr7-0WYV-Ym7DXnwpR9yyw

{
  "fname": "user2",
  "lname": "user2",
  "profilePic": "https://images-user2@gavatar.com",
  "contact": {
    "phone": "1234567890",
    "mobile": "1234567890"
  },
  "location": {
    "coordinates":[-73.856077, 40.848447],
    "address": "kwatule Road"
  }
}


GET http://{{hostname}}:{{port}}/credential
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmZhM2EzNzJiNDZlMjFiZjc3ZDI4YWUiLCJlbWFpbCI6InVzZXIyQGdtYWlsLmNvbSIsIm5hbWUiOiJ1c2VyMiIsImlhdCI6MTYxMDI5NTg4Nn0.bCt1cpyo3DKZUnhik6lafThR8iqqw0q_p1_ndHH8D9M



###
PUT http://{{hostname}}:{{port}}/credential
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmY0ODg1N2NjMTIzMTczMTdiYWJlYTciLCJlbWFpbCI6InVzZXJAeWFob28uY29tIiwibmFtZSI6InVzZXIiLCJpYXQiOjE2MDk4NjI2Mzl9.Xs0EXOffGPqU-r1B6gS46g2Wh0g_xKt0nFmMVcMK8cE

{
  "fname": "user2",
  "lname": "User2",
  "contact": {
    "phone": "+256771687717",
    "mobile":"+256238409388"
  }
}

# Technician routes

###
POST http://{{hostname}}:{{port}}/technicians
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmZhM2EzNzJiNDZlMjFiZjc3ZDI4YWUiLCJlbWFpbCI6InVzZXIyQHlhaG9vLmNvbSIsIm5hbWUiOiJ1c2VyMiIsImlhdCI6MTYxMDIzNDUyM30.dodpgdyW_es_PuR7iNaK6Cr7-0WYV-Ym7DXnwpR9yyw

{
  "rate": 5,
  "rating": 5.0,
  "status": "Avaible",
  "occupation": "Electrician",
  "experience": "20 years"
}